#!/usr/bin/env bash
#
# export-opnsense-api.sh — exporte les credentials OPNsense API.
#
# Sort 3 lignes :
#     OAF_OPNSENSE_URL=https://<IP>:4443
#     OAF_OPNSENSE_KEY=<clé>
#     OAF_OPNSENSE_SECRET=<secret>
#
# Lit les outputs Tofu (sensitive) sans demander de re-init.
#
# Usage :
#   bash scripts/export-opnsense-api.sh                   # imprime sur stdout
#   bash scripts/export-opnsense-api.sh > /tmp/oaf.env    # vers un fichier
#   . <(bash scripts/export-opnsense-api.sh)              # charge dans le shell courant
#
# Note de sécurité : la sortie contient le secret en clair. Ne jamais piper
# dans un fichier committé. /tmp/ est OK si nettoyé après usage.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="${SCRIPT_DIR}/../infra/envs/hcloud"

if [ ! -d "${TF_DIR}/.terraform" ]; then
    echo "Erreur : ${TF_DIR} n'a pas été 'tofu init'-ed." >&2
    echo "Run : (cd ${TF_DIR} && tofu init)" >&2
    exit 1
fi

IP=$(tofu -chdir="${TF_DIR}" output -raw opnsense_public_ip 2>/dev/null)
PORT=$(tofu -chdir="${TF_DIR}" output -raw -json 2>/dev/null | python3 -c '
import json,sys
o = json.load(sys.stdin)
ep = o.get("opnsense_api_endpoint", {}).get("value", "")
# extract :PORT
import re
m = re.search(r":(\d+)$", ep)
print(m.group(1) if m else "4443")
' 2>/dev/null || echo 4443)

KEY=$(tofu -chdir="${TF_DIR}" output -raw opnsense_api_key 2>/dev/null)
SECRET=$(tofu -chdir="${TF_DIR}" output -raw opnsense_api_secret 2>/dev/null)
USER=$(tofu -chdir="${TF_DIR}" output -raw opnsense_api_user 2>/dev/null)

if [ -z "$KEY" ] || [ -z "$SECRET" ]; then
    echo "Erreur : credentials API manquants dans les outputs Tofu." >&2
    echo "L'apply n'est peut-être pas terminé, ou les vars opnsense_api_key/_secret_plain sont vides dans tfvars." >&2
    exit 2
fi

cat <<EOF
# Generated by scripts/export-opnsense-api.sh on $(date -Iseconds)
# user OPNsense : ${USER} (member of group 'admins', priv 'page-all')
OAF_OPNSENSE_URL=https://${IP}:${PORT}
OAF_OPNSENSE_KEY=${KEY}
OAF_OPNSENSE_SECRET=${SECRET}
EOF
