#!/usr/bin/env bash
#
# export-opnsense-api.sh — exporte les credentials OPNsense API.
#
# Sort 3 lignes :
#     OAF_OPNSENSE_URL=https://<IP>:4443
#     OAF_OPNSENSE_KEY=<clé>
#     OAF_OPNSENSE_SECRET=<secret>
#
# Lit les outputs Tofu (sensitive) sans demander de re-init.
#
# Usage :
#   bash scripts/export-opnsense-api.sh                   # imprime sur stdout
#   bash scripts/export-opnsense-api.sh > /tmp/oaf.env    # vers un fichier
#   . <(bash scripts/export-opnsense-api.sh)              # charge dans le shell courant
#
# Note de sécurité : la sortie contient le secret en clair. Ne jamais piper
# dans un fichier committé. /tmp/ est OK si nettoyé après usage.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="${SCRIPT_DIR}/../infra/envs/hcloud"

if [ ! -d "${TF_DIR}/.terraform" ]; then
    echo "Erreur : ${TF_DIR} n'a pas été 'tofu init'-ed." >&2
    echo "Run : (cd ${TF_DIR} && tofu init)" >&2
    exit 1
fi

# Helper : lit un output tofu en mode -raw, ou stderr + exit avec message
# explicite si l'output n'existe pas dans le state (cas typique : tofu
# apply n'a pas été refait depuis l'ajout des outputs).
read_tf_output() {
    local name="$1"
    local out
    if ! out=$(tofu -chdir="${TF_DIR}" output -raw "${name}" 2>&1); then
        echo "Erreur : output Tofu '${name}' introuvable dans le state." >&2
        echo "Détail : ${out}" >&2
        echo "Fix : relancer 'tofu apply' depuis ${TF_DIR} pour materialiser les outputs récemment ajoutés." >&2
        exit 2
    fi
    printf '%s' "${out}"
}

IP=$(read_tf_output opnsense_public_ip)
KEY=$(read_tf_output opnsense_api_key)
SECRET=$(read_tf_output opnsense_api_secret)
USER=$(read_tf_output opnsense_api_user)
ENDPOINT=$(read_tf_output opnsense_api_endpoint)

cat <<EOF
# Generated by scripts/export-opnsense-api.sh on $(date -Iseconds)
# user OPNsense : ${USER} (member of group 'admins', priv 'page-all')
OAF_OPNSENSE_URL=${ENDPOINT}
OAF_OPNSENSE_KEY=${KEY}
OAF_OPNSENSE_SECRET=${SECRET}
EOF
