"""
tools_catalog.py — catalogue auto-généré des fonctions OPNsense
que le LoRA `opnsense-agent-phi35` peut produire en tool_call.

GÉNÉRÉ AUTOMATIQUEMENT par scripts/generate-tools-catalog.py
à partir du repo cyber-agent-engine. Ne PAS éditer à la main —
modifier les sources et re-générer.

Source : verify_opnsense_v2.py (102 directives canoniques run v7).
Catalogue : 97 / 102 fonctions résolues
vers une méthode client OPNsense.
"""

from __future__ import annotations

# Mapping nom canonique (LoRA) → (méthode HTTP, endpoint OPNsense REST, mutating bool)
# Pour les noms LoRA qui diffèrent du nom client (ex: del_X côté LoRA →
# delete_X côté client), le mapping est résolu par alias automatique.
TOOLS_CATALOG: dict[str, tuple[str, str, bool]] = {
    "add_alias": ("POST", "/api/firewall/alias/addItem", True),
    "add_category": ("POST", "/api/firewall/category/addItem", True),
    "add_dns_override": ("POST", "/api/unbound/settings/addHostOverride", True),
    "add_filter_rule": ("POST", "/api/firewall/filter/addRule", True),
    "add_nat_one_to_one": ("POST", "/api/firewall/one_to_one/addRule", True),
    "add_nat_outbound": ("POST", "/api/firewall/source_nat/addRule", True),
    "add_nat_port_forward": ("POST", "/api/firewall/filter/addRule", True),
    "add_static_mapping": ("POST", "/api/dhcpv4/settings/addStaticMapping", True),
    "add_static_route": ("POST", "/api/routes/routes/addroute", True),
    "add_to_alias": ("POST", "/api/firewall/alias_util/add/{alias_name}", False),
    "add_traffic_pipe": ("POST", "/api/trafficshaper/settings/addPipe", True),
    "add_traffic_queue": ("POST", "/api/trafficshaper/settings/addQueue", True),
    "add_traffic_rule": ("POST", "/api/trafficshaper/settings/addRule", True),
    "apply_firewall_changes": ("POST", "/api/firewall/filter/apply", True),
    "apply_traffic_changes": ("POST", "/api/trafficshaper/service/reconfigure", False),
    "block_ip": ("POST", "/api/firewall/filter/addRule", True),
    "cancel_firewall_rollback": ("POST", "/api/firewall/filter_base/cancel_rollback", False),
    "check_updates": ("POST", "/api/core/firmware/check", False),
    "connect_ipsec_session": ("POST", "/api/ipsec/sessions/connect/{session_id}", False),
    "create_firewall_savepoint": ("POST", "/api/firewall/filter_base/savepoint", True),
    "del_alias": ("POST", "/api/firewall/alias/delItem/{uuid}", False),
    "del_category": ("POST", "/api/firewall/category/delItem/{uuid}", False),
    "del_dns_override": ("POST", "/api/unbound/settings/delHostOverride/{uuid}", False),
    "del_filter_rule": ("POST", "/api/firewall/filter/delRule/{uuid}", False),
    "del_from_alias": ("POST", "/api/firewall/alias_util/delete/{alias_name}", False),
    "del_nat_one_to_one": ("POST", "/api/firewall/one_to_one/delRule/{uuid}", False),
    "del_nat_outbound": ("POST", "/api/firewall/source_nat/delRule/{uuid}", False),
    "del_static_route": ("POST", "/api/routes/routes/delroute/{uuid}", False),
    "del_traffic_pipe": ("POST", "/api/trafficshaper/settings/delPipe/{uuid}", False),
    "del_traffic_queue": ("POST", "/api/trafficshaper/settings/delQueue/{uuid}", False),
    "del_traffic_rule": ("POST", "/api/trafficshaper/settings/delRule/{uuid}", False),
    "disconnect_ipsec_session": ("POST", "/api/ipsec/sessions/disconnect/{session_id}", False),
    "find_alias_references": ("GET", "/api/firewall/alias_util/find_references", False),
    "flush_alias": ("POST", "/api/firewall/alias_util/flush/{alias_name}", False),
    "flush_firewall_states": ("POST", "/api/diagnostics/firewall/flush_states", True),
    "get_acme_status": ("GET", "/api/acmeclient/service/status", False),
    "get_alias": ("GET", "/api/firewall/alias/getItem/{uuid}", False),
    "get_cron_jobs": ("GET", "/api/cron/settings/searchJobs", False),
    "get_dhcp_leases": ("GET", "/api/dhcpv4/leases/searchLease", False),
    "get_filter_rule": ("GET", "/api/firewall/filter/getRule/{uuid}", False),
    "get_firewall_log": ("GET", "/api/diagnostics/firewall/log", False),
    "get_firewall_states": ("GET", "/api/diagnostics/firewall/pf_states", False),
    "get_firewall_statistics": ("GET", "/api/diagnostics/firewall/pf_statistics", False),
    "get_geoip_database": ("GET", "/api/firewall/alias/get_geoip", False),
    "get_ids_status": ("GET", "/api/ids/service/status", False),
    "get_interface_list": ("GET", "/api/firewall/filter/get", False),
    "get_ipsec_status": ("GET", "/api/ipsec/service/status", False),
    "get_monit_status": ("GET", "/api/monit/status/get", False),
    "get_rule_statistics": ("GET", "/api/firewall/filter_util/rule_stats", False),
    "get_static_routes": ("POST", "/api/routes/routes/searchroute", False),
    "get_traffic_statistics": ("GET", "/api/trafficshaper/service/statistics", False),
    "get_upgrade_status": ("GET", "/api/core/firmware/status", False),
    "kill_firewall_states": ("POST", "/api/diagnostics/firewall/kill_states", True),
    "kill_openvpn_session": ("POST", "/api/openvpn/service/killSession", True),
    "list_acme_accounts": ("GET", "/api/acmeclient/accounts/get", False),
    "list_acme_certificates": ("GET", "/api/acmeclient/certificates/get", False),
    "list_alias_content": ("GET", "/api/firewall/alias_util/list/{alias_name}", False),
    "list_categories": ("GET", "/api/firewall/category/get", False),
    "list_dns_overrides": ("POST", "/api/unbound/settings/searchHostOverride", False),
    "list_geoip_countries": ("GET", "/api/firewall/alias/list_countries", False),
    "list_ids_rulesets": ("GET", "/api/ids/settings/listRulesets", False),
    "list_ipsec_connections": ("GET", "/api/ipsec/connections/get", False),
    "list_ipsec_sessions": ("GET", "/api/ipsec/sessions/searchPhase1", False),
    "list_openvpn_instances": ("GET", "/api/openvpn/instances/get", False),
    "list_openvpn_sessions": ("GET", "/api/openvpn/service/searchSessions", False),
    "list_restore_points": ("GET", "/api/core/backup/backups/this", False),
    "list_traffic_pipes": ("GET", "/api/trafficshaper/settings/getPipe", False),
    "list_traffic_queues": ("GET", "/api/trafficshaper/settings/getQueue", False),
    "list_traffic_rules": ("GET", "/api/trafficshaper/settings/getRule", False),
    "manage_dns_blocklist": ("POST", "/api/unbound/settings/set", True),
    "ping_host": ("POST", "/api/diagnostics/ping/set", True),
    "port_probe": ("POST", "/api/diagnostics/portprobe/set", True),
    "query_ids_alerts": ("POST", "/api/ids/service/queryAlerts", False),
    "restart_ids": ("POST", "/api/ids/service/restart", True),
    "restart_monit_service": ("POST", "/api/monit/status/setAction", True),
    "revert_firewall_changes": ("POST", "/api/firewall/filter_base/revert", True),
    "revert_to_restore_point": ("POST", "/api/core/backup/revert/{revision_id}", False),
    "revoke_acme_certificate": ("POST", "/api/acmeclient/certificates/revoke/{uuid}", False),
    "schedule_cron_job": ("POST", "/api/cron/settings/addJob", True),
    "search_dns_queries": ("POST", "/api/unbound/diagnostics/search", False),
    "set_alias": ("POST", "/api/firewall/alias/setItem/{uuid}", False),
    "set_filter_rule": ("POST", "/api/firewall/filter/setRule/{uuid}", False),
    "sign_acme_certificate": ("POST", "/api/acmeclient/certificates/sign/{uuid}", False),
    "start_ids": ("POST", "/api/ids/service/start", False),
    "stop_ids": ("POST", "/api/ids/service/stop", False),
    "toggle_cron_job": ("POST", "/api/cron/settings/toggleJob/{uuid}/{enabled}", False),
    "toggle_filter_rule": ("POST", "/api/firewall/filter/toggleRule/{uuid}/{enabled}", False),
    "toggle_ids_rule": ("POST", "/api/ids/settings/toggleRule", True),
    "toggle_ids_ruleset": ("POST", "/api/ids/settings/toggleRuleset/{filename}/{enabled}", False),
    "toggle_ipsec_connection": ("POST", "/api/ipsec/connections/toggleConnection/{uuid}/{enabled}", False),
    "toggle_openvpn_instance": ("POST", "/api/openvpn/instances/toggle/{uuid}/{enabled}", False),
    "traceroute_host": ("POST", "/api/diagnostics/traceroute/set", True),
    "unblock_ip": ("POST", "/api/firewall/filter/delRule/{uuid}", False),
    "update_acme_certificate": ("POST", "/api/acmeclient/certificates/update/{uuid}", False),
    "update_bogons": ("POST", "/api/firewall/alias_util/update_bogons", True),
    "update_ids_rules": ("POST", "/api/ids/service/updateRules", True),
    "upgrade_firmware": ("POST", "/api/core/firmware/upgrade", False),
}

# Descriptions OpenAI-style (les schemas parameters complets
# ne sont pas embarqués ici — pour l'API tool-calling on
# envoie juste le name et une description textuelle).
TOOL_DESCRIPTIONS: dict[str, str] = {
    "add_alias": "Add a new alias",
    "add_category": "Crée une nouvelle catégorie de règles dans OPNsense.",
    "add_dns_override": "Add a new Unbound DNS Host Override (A record).",
    "add_filter_rule": "OPNsense action add_filter_rule",
    "add_nat_one_to_one": "OPNsense action add_nat_one_to_one",
    "add_nat_outbound": "OPNsense action add_nat_outbound",
    "add_nat_port_forward": "Crée une règle NAT ENTRANT (DNAT) : redirige le trafic VENANT D'INTERNET vers un serveur interne. SENS OPPOSÉ de add_nat_outbound (qui masque les IPs des machines INTERNES vers internet) : add_nat_por",
    "add_static_mapping": "Add a static DHCPv4 mapping (reservation) for a specific MAC address.",
    "add_static_route": "Add a new static route",
    "add_to_alias": "Ajoute une adresse IP ou un réseau à un alias existant.",
    "add_traffic_pipe": "Crée un pipe de traffic shaping pour limiter la bande passante d'un flux réseau. NE PAS CONFONDRE avec add_traffic_rule (qui classifie le trafic) ou add_traffic_queue (sous-division d'un pipe) : add_t",
    "add_traffic_queue": "Crée une queue de priorisation attachée à un pipe existant. NE PAS CONFONDRE avec add_traffic_pipe (qui crée le limiteur de débit parent) : add_traffic_queue nécessite l'UUID d'un pipe existant. Si la",
    "add_traffic_rule": "Crée une règle classifiant le trafic (source/destination) vers un pipe ou une queue. NE PAS CONFONDRE avec add_filter_rule (règle firewall block/pass) ou add_traffic_pipe (limiteur de débit) : add_tra",
    "apply_firewall_changes": "OPNsense action apply_firewall_changes",
    "apply_traffic_changes": "Applique et active toutes les modifications de traffic shaping en attente (reconfigure dummynet). NE PAS CONFONDRE avec apply_firewall_changes (qui applique les règles firewall) : apply_traffic_change",
    "block_ip": "Bloque une adresse IP via une règle de pare-feu OPNsense.",
    "cancel_firewall_rollback": "CONFIRME et MAINTIENT les changements de règles firewall pendant un rollback automatique en cours — annule le rollback. NE PAS CONFONDRE avec revert_firewall_changes (qui ANNULE des changements non ap",
    "check_updates": "OPNsense action check_updates",
    "connect_ipsec_session": "Initie activement une session IPsec (établit le tunnel). NE PAS CONFONDRE avec toggle_ipsec_connection (active/désactive la config) : connect_ipsec_session = ordonne l'établissement immédiat du tunnel",
    "create_firewall_savepoint": "Crée un point de sauvegarde temporaire pour les règles firewall uniquement (avant un test). Différent d'un snapshot système complet.",
    "del_alias": "OPNsense action del_alias",
    "del_category": "Supprime une catégorie OPNsense par UUID.",
    "del_dns_override": "Supprime un override DNS (entrée personnalisée) dans OPNsense.",
    "del_filter_rule": "OPNsense action del_filter_rule",
    "del_from_alias": "Supprime une adresse IP ou un réseau d'un alias existant.",
    "del_nat_one_to_one": "OPNsense action del_nat_one_to_one",
    "del_nat_outbound": "OPNsense action del_nat_outbound",
    "del_static_route": "OPNsense action del_static_route",
    "del_traffic_pipe": "Supprime un pipe de traffic shaping par son UUID. NE PAS CONFONDRE avec del_traffic_rule ou del_traffic_queue : del_traffic_pipe = suppression du pipe (limiteur de débit). Si la demande mentionne supp",
    "del_traffic_queue": "Supprime une queue de traffic shaping par son UUID. NE PAS CONFONDRE avec del_traffic_pipe (suppression du limiteur parent) : del_traffic_queue = suppression d'une queue de priorité. Si la demande men",
    "del_traffic_rule": "Supprime une règle de classification du trafic QoS par son UUID. NE PAS CONFONDRE avec del_filter_rule (suppression de règle firewall) : del_traffic_rule = règle QoS. del_filter_rule = règle firewall ",
    "disconnect_ipsec_session": "Déconnecte et ferme une session IPsec active (coupe le tunnel). NE PAS CONFONDRE avec toggle_ipsec_connection (désactivation de la config) : disconnect_ipsec_session = coupe le tunnel actif immédiatem",
    "find_alias_references": "Recherche toutes les règles qui référencent un alias donné.",
    "flush_alias": "Vide TOUT le contenu d'un alias (toutes ses adresses) en une seule opération, sans supprimer l'alias. NE PAS CONFONDRE avec delete_from_alias (qui retire UN SEUL élément spécifique du contenu) : flush",
    "flush_firewall_states": "Purge toutes les connexions actives de la table d'états du pare-feu.",
    "get_acme_status": "Vérifie l'état du service ACME client (plugin Let's Encrypt OPNsense). NE PAS CONFONDRE avec list_acme_certificates (qui liste les certificats) : get_acme_status = est-ce que le service tourne ? list_",
    "get_alias": "Get alias details",
    "get_cron_jobs": "Get list of all scheduled Cron jobs",
    "get_dhcp_leases": "OPNsense action get_dhcp_leases",
    "get_filter_rule": "CONSULTE les détails d'une règle de filtrage existante (opération de LECTURE, non destructive). NE PAS CONFONDRE avec del_filter_rule (qui SUPPRIME la règle définitivement) : get_filter_rule retourne ",
    "get_firewall_log": "OPNsense action get_firewall_log",
    "get_firewall_states": "Liste les connexions actives dans la table d'états du pare-feu OPNsense (lecture seule).",
    "get_firewall_statistics": "Retourne des STATISTIQUES DE TRAFIC agrégées : compteurs de paquets, octets, hits par interface ou règle. NE PAS CONFONDRE avec get_firewall_states (qui liste les CONNEXIONS ACTIVES en cours, pas des ",
    "get_geoip_database": "Consulte le statut de la base de données GeoIP : version, date de mise à jour, nombre d'entrées. Aucun rapport avec upgrade_firmware (mise à jour du firmware/système OPNsense) : get_geoip_database con",
    "get_ids_status": "Get Suricata IDS service status",
    "get_interface_list": "OPNsense action get_interface_list",
    "get_ipsec_status": "Retourne l'état du service IPsec (strongSwan) et le nombre de tunnels actifs. NE PAS CONFONDRE avec list_ipsec_sessions (qui liste les sessions actives) : get_ipsec_status = état global du service. li",
    "get_monit_status": "Get Monit services status",
    "get_rule_statistics": "OPNsense action get_rule_statistics",
    "get_static_routes": "List configured static routes",
    "get_traffic_statistics": "Retourne les statistiques de bande passante en temps réel par pipe et queue (octets, paquets traités). NE PAS CONFONDRE avec get_firewall_statistics (compteurs de règles firewall) : get_traffic_statis",
    "get_upgrade_status": "Retourne le STATUT EN COURS d'une mise à jour firmware déjà lancée (progression, logs, état). NE PAS CONFONDRE avec upgrade_firmware (qui LANCE la mise à jour) ou check_updates (qui vérifie la disponi",
    "kill_firewall_states": "Supprime des connexions actives spécifiques dans la table d'états du pare-feu.",
    "kill_openvpn_session": "Déconnecte de force un client OpenVPN par son Common Name et son adresse IP. NE PAS CONFONDRE avec toggle_openvpn_instance (désactive le serveur entier) : kill_openvpn_session = éjecte UN client. togg",
    "list_acme_accounts": "Liste les comptes ACME (Let's Encrypt) configurés sur OPNsense (adresses email d'enregistrement). NE PAS CONFONDRE avec list_acme_certificates (qui liste les certificats, pas les comptes) : list_acme_",
    "list_acme_certificates": "Liste tous les certificats TLS gérés par le client ACME (Let's Encrypt) avec domaines et dates d'expiration. NE PAS CONFONDRE avec get_acme_status (état du service) ou sign_acme_certificate (renouvell",
    "list_alias_content": "List all aliases",
    "list_categories": "OPNsense action list_categories",
    "list_dns_overrides": "List all Unbound DNS Host Overrides (A records).",
    "list_geoip_countries": "Liste tous les pays disponibles dans la base GeoIP d'OPNsense.",
    "list_ids_rulesets": "Liste les rulesets IDS Suricata disponibles (Emerging Threats, Snort, etc.) avec leur état d'activation. NE PAS CONFONDRE avec query_ids_alerts (qui retourne les alertes déclenchées) ou get_ids_status",
    "list_ipsec_connections": "Liste toutes les connexions IPsec configurées (site-to-site, road warrior) avec leur UUID et statut. NE PAS CONFONDRE avec list_ipsec_sessions (qui liste les sessions ACTIVES établies) : list_ipsec_co",
    "list_ipsec_sessions": "Liste les sessions IPsec actives (tunnels phase 1 établis) avec IPs locales et distantes. NE PAS CONFONDRE avec list_ipsec_connections (configuration) : list_ipsec_sessions = tunnels ACTUELLEMENT étab",
    "list_openvpn_instances": "Liste toutes les instances OpenVPN configurées (serveurs et clients) avec UUID et état. NE PAS CONFONDRE avec list_openvpn_sessions (qui liste les clients connectés) : list_openvpn_instances = configu",
    "list_openvpn_sessions": "Liste les sessions OpenVPN actives (clients VPN actuellement connectés) avec CN et IP. NE PAS CONFONDRE avec list_openvpn_instances (configuration des serveurs) : list_openvpn_sessions = qui est conne",
    "list_restore_points": "OPNsense action list_restore_points",
    "list_traffic_pipes": "Liste tous les pipes de traffic shaping configurés (limitations de bande passante). NE PAS CONFONDRE avec list_traffic_queues (qui liste les queues de priorisation) : list_traffic_pipes = voir les lim",
    "list_traffic_queues": "Liste toutes les queues de traffic shaping (priorisation intra-pipe). NE PAS CONFONDRE avec list_traffic_pipes (les limiteurs de débit) : list_traffic_queues = voir les priorités à l'intérieur d'un pi",
    "list_traffic_rules": "Liste les règles de classification du trafic (quelles IPs/ports vont dans quel pipe). NE PAS CONFONDRE avec get_filter_rule (règles firewall block/pass) : list_traffic_rules = règles QoS de routage ve",
    "manage_dns_blocklist": "Manage Unbound DNS blocklist state",
    "ping_host": "Ping a remote host",
    "port_probe": "Test TCP port connectivity on a remote host",
    "query_ids_alerts": "Interroge les journaux d'alertes IDS (Suricata). Utile pour voir quelles adresses IP déclenchent des règles de détection.",
    "restart_ids": "Redémarre le service IDS Suricata pour appliquer les changements de configuration. NE PAS CONFONDRE avec update_ids_rules (qui met à jour les signatures sans redémarrer) : restart_ids = redémarre le d",
    "restart_monit_service": "Restart a service managed by Monit",
    "revert_firewall_changes": "OPNsense action revert_firewall_changes",
    "revert_to_restore_point": "OPNsense action revert_to_restore_point",
    "revoke_acme_certificate": "Révoque un certificat ACME auprès de l'autorité de certification (Let's Encrypt). NE PAS CONFONDRE avec update_acme_certificate (renouvellement) : revoke_acme_certificate = révocation définitive (le c",
    "schedule_cron_job": "Schedule a new Cron job",
    "search_dns_queries": "Recherche dans l'historique des requêtes DNS Unbound.",
    "set_alias": "Modifie les MÉTADONNÉES d'un alias : son nom, son type ou sa description (la définition de l'alias). NE PAS CONFONDRE avec add_to_alias (qui ajoute une IP/hôte dans le CONTENU de l'alias) : set_alias ",
    "set_filter_rule": "Modifie une règle de filtrage pare-feu existante dans OPNsense.",
    "sign_acme_certificate": "Déclenche la demande ou le renouvellement d'un certificat Let's Encrypt via challenge ACME. NE PAS CONFONDRE avec update_acme_certificate (mise à jour forcée) : sign_acme_certificate = premier challen",
    "start_ids": "Démarre le service IDS Suricata s'il est arrêté. NE PAS CONFONDRE avec restart_ids (qui redémarre un service déjà actif) : start_ids = démarrage initial. restart_ids = redémarrage. Si la demande menti",
    "stop_ids": "Arrête le service IDS Suricata. NE PAS CONFONDRE avec restart_ids (redémarrage) ou toggle_ids_ruleset (désactivation d'un ruleset) : stop_ids = arrêt complet du daemon. Si la demande mentionne arrêter",
    "toggle_cron_job": "Enable or disable a Cron job",
    "toggle_filter_rule": "Toggle a firewall rule (enable/disable)",
    "toggle_ids_rule": "Enable or disable an IDS rule signature",
    "toggle_ids_ruleset": "Active ou désactive un ruleset IDS entier (ex: emerging-threats.rules) par son nom de fichier. NE PAS CONFONDRE avec toggle_ids_rule (qui agit sur UNE règle par SID) : toggle_ids_ruleset = un jeu comp",
    "toggle_ipsec_connection": "Active ou désactive une connexion IPsec par son UUID. NE PAS CONFONDRE avec connect_ipsec_session (qui établit activement un tunnel) : toggle_ipsec_connection = activer/désactiver la config. connect_i",
    "toggle_openvpn_instance": "Active ou désactive une instance OpenVPN (serveur ou client) par son UUID. NE PAS CONFONDRE avec kill_openvpn_session (qui déconnecte un client connecté) : toggle_openvpn_instance = active/désactive l",
    "traceroute_host": "Traceroute to a remote host",
    "unblock_ip": "Débloque une adresse IP précédemment bloquée via block_ip.",
    "update_acme_certificate": "Force la mise à jour d'un certificat ACME existant (re-challenge sans recréer la config). NE PAS CONFONDRE avec sign_acme_certificate (première émission) ou revoke_acme_certificate (révocation) : upda",
    "update_bogons": "OPNsense action update_bogons",
    "update_ids_rules": "Télécharge et met à jour les règles IDS depuis les sources upstream (Emerging Threats, Snort Community, etc.). NE PAS CONFONDRE avec restart_ids (qui redémarre le service sans changer les règles) : up",
    "upgrade_firmware": "Start a system firmware upgrade.",
}

# Noms canoniques (verify_v2) qui n'ont pas pu être résolus
# vers une méthode client. À traiter au cas par cas dans
# TOOLS_LOCAL_OVERRIDES de oaf_agent.py (peut nécessiter un
# ARG_ADAPTERS pour composer la requête sur le client).
CANONICAL_UNMAPPED: frozenset[str] = frozenset({
    "backup_configuration",
    "create_restore_point",
    "get_system_status",
    "import_alias",
    "move_filter_rule",
})

# Noms training mais hors des 102 canoniques (synthétiques /
# aliases / variantes vues en augmentation training). Utilisés
# par l'agent pour distinguer 'hallucination' de 'connu mais
# hors scope verify'.
KNOWN_UNMAPPED: frozenset[str] = frozenset({
    "delete_static_route",
    "diagnostics_dns_reverse_lookup",
    "diagnostics_interface_carp_status",
    "diagnostics_interface_del_route",
    "diagnostics_interface_flush_arp",
    "diagnostics_interface_get_arp",
    "diagnostics_interface_get_bpf_statistics",
    "diagnostics_interface_get_interface_config",
    "diagnostics_interface_get_interface_names",
    "diagnostics_interface_get_interface_statistics",
    "diagnostics_interface_get_memory_statistics",
    "diagnostics_interface_get_ndp",
    "diagnostics_interface_get_netisr_statistics",
    "diagnostics_interface_get_pfsync_nodes",
    "diagnostics_interface_get_protocol_statistics",
    "diagnostics_interface_get_routes",
    "diagnostics_interface_get_socket_statistics",
    "diagnostics_interface_get_vip_status",
    "diagnostics_interface_search_arp",
    "diagnostics_interface_search_ndp",
    "diagnostics_netflow_cache_stats",
    "diagnostics_netflow_getconfig",
    "diagnostics_netflow_is_enabled",
    "diagnostics_netflow_reconfigure",
    "diagnostics_netflow_setconfig",
    "diagnostics_netflow_status",
    "diagnostics_packet_capture_download",
    "diagnostics_packet_capture_get",
    "diagnostics_packet_capture_mac_info",
    "diagnostics_packet_capture_remove",
    "diagnostics_packet_capture_search_jobs",
    "diagnostics_packet_capture_set",
    "diagnostics_packet_capture_start",
    "diagnostics_packet_capture_stop",
    "diagnostics_packet_capture_view",
    "diagnostics_ping_get",
    "diagnostics_ping_remove",
    "diagnostics_ping_search_jobs",
    "diagnostics_ping_set",
    "diagnostics_ping_start",
    "diagnostics_ping_stop",
    "diagnostics_system_memory",
    "diagnostics_system_system_disk",
    "diagnostics_system_system_information",
    "diagnostics_system_system_mbuf",
    "diagnostics_system_system_resources",
    "diagnostics_system_system_swap",
    "diagnostics_system_system_temperature",
    "diagnostics_system_system_time",
    "diagnostics_traceroute_get",
    "diagnostics_traceroute_set",
    "firewall_alias_add_item",
    "firewall_alias_del_item",
    "firewall_alias_get",
    "firewall_alias_get_alias_u_u_i_d",
    "firewall_alias_get_geo_i_p",
    "firewall_alias_get_item",
    "firewall_alias_get_table_size",
    "firewall_alias_import",
    "firewall_alias_list_categories",
    "firewall_alias_list_countries",
    "firewall_alias_list_network_aliases",
    "firewall_alias_list_user_groups",
    "firewall_alias_reconfigure",
    "firewall_alias_set",
    "firewall_alias_set_item",
    "firewall_alias_toggle_item",
    "firewall_alias_util_add",
    "firewall_alias_util_aliases",
    "firewall_alias_util_delete",
    "firewall_alias_util_find_references",
    "firewall_alias_util_flush",
    "firewall_alias_util_list",
    "firewall_alias_util_update_bogons",
    "firewall_filter_add_rule",
    "firewall_filter_base_apply",
    "firewall_filter_base_cancel_rollback",
    "firewall_filter_base_get",
    "firewall_filter_base_list_categories",
    "firewall_filter_base_list_network_select_options",
    "firewall_filter_base_revert",
    "firewall_filter_base_savepoint",
    "firewall_filter_base_set",
    "firewall_filter_del_rule",
    "firewall_filter_get_interface_list",
    "firewall_filter_get_rule",
    "firewall_filter_move_rule_before",
    "firewall_filter_set_rule",
    "firewall_filter_toggle_rule",
    "firewall_group_add_item",
    "firewall_group_del_item",
    "firewall_group_get",
    "firewall_group_get_item",
    "firewall_group_reconfigure",
    "firewall_group_set",
    "firewall_group_set_item",
    "firewall_npt_add_rule",
    "firewall_npt_del_rule",
    "firewall_npt_get_rule",
    "firewall_npt_set_rule",
    "firewall_npt_toggle_rule",
    "firewall_one_to_one_add_rule",
    "firewall_one_to_one_del_rule",
    "firewall_one_to_one_get_rule",
    "firewall_one_to_one_set_rule",
    "firewall_one_to_one_toggle_rule",
    "firewall_source_nat_add_rule",
    "firewall_source_nat_del_rule",
    "firewall_source_nat_get_rule",
    "firewall_source_nat_set_rule",
    "firewall_source_nat_toggle_rule",
    "ids_service_drop_alert_log",
    "ids_service_get_alert_info",
    "ids_service_get_alert_logs",
    "ids_service_query_alerts",
    "ids_service_reconfigure",
    "ids_service_reload_rules",
    "ids_service_restart",
    "ids_service_start",
    "ids_service_status",
    "ids_service_stop",
    "ids_service_update_rules",
    "ids_settings_add_policy",
    "ids_settings_add_policy_rule",
    "ids_settings_add_user_rule",
    "ids_settings_check_policy_rule",
    "ids_settings_del_policy",
    "ids_settings_del_policy_rule",
    "ids_settings_del_user_rule",
    "ids_settings_get",
    "ids_settings_get_policy",
    "ids_settings_get_policy_rule",
    "ids_settings_get_rule_info",
    "ids_settings_get_ruleset",
    "ids_settings_get_rulesetproperties",
    "ids_settings_get_user_rule",
    "ids_settings_list_rule_metadata",
    "ids_settings_list_rulesets",
    "ids_settings_search_installed_rules",
    "ids_settings_set",
    "ids_settings_set_policy",
    "ids_settings_set_policy_rule",
    "ids_settings_set_rule",
    "ids_settings_set_ruleset",
    "ids_settings_set_rulesetproperties",
    "ids_settings_set_user_rule",
    "ids_settings_toggle_policy",
    "ids_settings_toggle_policy_rule",
    "ids_settings_toggle_rule",
    "ids_settings_toggle_ruleset",
    "ids_settings_toggle_user_rule",
    "ipsec_connections_add_child",
    "ipsec_connections_add_connection",
    "ipsec_connections_add_local",
    "ipsec_connections_add_remote",
    "ipsec_connections_connection_exists",
    "ipsec_connections_del_child",
    "ipsec_connections_del_connection",
    "ipsec_connections_del_local",
    "ipsec_connections_del_remote",
    "ipsec_connections_get",
    "ipsec_connections_get_child",
    "ipsec_connections_get_connection",
    "ipsec_connections_get_local",
    "ipsec_connections_get_remote",
    "ipsec_connections_is_enabled",
    "ipsec_connections_set",
    "ipsec_connections_set_child",
    "ipsec_connections_set_connection",
    "ipsec_connections_set_local",
    "ipsec_connections_set_remote",
    "ipsec_connections_swanctl",
    "ipsec_connections_toggle",
    "ipsec_connections_toggle_child",
    "ipsec_connections_toggle_connection",
    "ipsec_connections_toggle_local",
    "ipsec_connections_toggle_remote",
    "ipsec_legacy_subsystem_apply_config",
    "ipsec_legacy_subsystem_status",
    "ipsec_sessions_connect",
    "ipsec_sessions_disconnect",
    "ipsec_sessions_search_phase1",
    "ipsec_sessions_search_phase2",
    "ipsec_tunnel_del_phase1",
    "ipsec_tunnel_del_phase2",
    "ipsec_tunnel_search_phase1",
    "ipsec_tunnel_search_phase2",
    "ipsec_tunnel_toggle",
    "ipsec_tunnel_toggle_phase1",
    "ipsec_tunnel_toggle_phase2",
    "ipsec_vti_add",
    "ipsec_vti_del",
    "ipsec_vti_get",
    "ipsec_vti_set",
    "ipsec_vti_toggle",
    "openvpn_client_overwrites_add",
    "openvpn_client_overwrites_del",
    "openvpn_client_overwrites_get",
    "openvpn_client_overwrites_set",
    "openvpn_client_overwrites_toggle",
    "openvpn_export_accounts",
    "openvpn_export_download",
    "openvpn_export_providers",
    "openvpn_export_store_presets",
    "openvpn_export_templates",
    "openvpn_export_validate_presets",
    "openvpn_instances_add",
    "openvpn_instances_add_static_key",
    "openvpn_instances_del",
    "openvpn_instances_del_static_key",
    "openvpn_instances_gen_key",
    "openvpn_instances_get",
    "openvpn_instances_get_static_key",
    "openvpn_instances_set",
    "openvpn_instances_set_static_key",
    "openvpn_instances_toggle",
    "openvpn_service_kill_session",
    "openvpn_service_reconfigure",
    "openvpn_service_restart_service",
    "openvpn_service_search_routes",
    "openvpn_service_search_sessions",
    "openvpn_service_start_service",
    "openvpn_service_stop_service",
    "unbound_service_dnsbl",
    "unbound_service_reconfigure",
    "unbound_service_reconfigure_general",
    "unbound_service_restart",
    "unbound_service_start",
    "unbound_service_status",
    "unbound_service_stop",
    "unbound_settings_add_acl",
    "unbound_settings_add_forward",
    "unbound_settings_add_host_alias",
    "unbound_settings_add_host_override",
    "unbound_settings_del_acl",
    "unbound_settings_del_forward",
    "unbound_settings_del_host_alias",
    "unbound_settings_del_host_override",
    "unbound_settings_get",
    "unbound_settings_get_acl",
    "unbound_settings_get_forward",
    "unbound_settings_get_host_alias",
    "unbound_settings_get_host_override",
    "unbound_settings_get_nameservers",
    "unbound_settings_set",
    "unbound_settings_set_acl",
    "unbound_settings_set_forward",
    "unbound_settings_set_host_alias",
    "unbound_settings_set_host_override",
    "unbound_settings_toggle_acl",
    "unbound_settings_toggle_forward",
    "unbound_settings_toggle_host_alias",
    "unbound_settings_toggle_host_override",
    "unbound_settings_update_blocklist",
    "wireguard_client_add_client",
    "wireguard_client_add_client_builder",
    "wireguard_client_del_client",
    "wireguard_client_get",
    "wireguard_client_get_client",
    "wireguard_client_get_client_builder",
    "wireguard_client_get_server_info",
    "wireguard_client_list_servers",
    "wireguard_client_psk",
    "wireguard_client_set",
    "wireguard_client_set_client",
    "wireguard_client_toggle_client",
    "wireguard_general_get",
    "wireguard_general_set",
    "wireguard_server_add_server",
    "wireguard_server_del_server",
    "wireguard_server_get",
    "wireguard_server_get_server",
    "wireguard_server_key_pair",
    "wireguard_server_set",
    "wireguard_server_set_server",
    "wireguard_server_toggle_server",
    "wireguard_service_reconfigure",
    "wireguard_service_restart",
    "wireguard_service_show",
    "wireguard_service_start",
    "wireguard_service_status",
    "wireguard_service_stop",
})

